### PR TITLE
Add nft-bam version 0.1.0

### PR DESCRIPTION
**Pull request by nvnieuwk**
Hi @lukfor and @seppinho can one of you please take a look at this? I've created a simple plugin to help out with some commonly occuring problems with SAM/BAM/CRAM files in nf-core.

### CODE REVIEW

**Comment by lukfor** [comment]
Yeah, thanks! I will add it asap. Thanks for your help 🙏

**Comment by lukfor** [comment]
Btw: the API is super designed and documented. I love it :)

**Comment by nvnieuwk** [comment]
Thank you for the kind words! :partying_face:

**Comment by nvnieuwk** [comment]
Thank you @lukfor :partying_face:

**Comment by lukfor** [comment]
In case nf-test has issues finding the plugin, try to delete the `.nf-test` subdirectory. The plugin mechanism has not yet the best caching mechanism implemented 🙈

It's also listed automatically on the plugins site: https://plugins.nf-test.com

Thanks again!

**Comment by nvnieuwk** [comment]
I just tried it out and it worked immediately and perfectly :)

**Pull request merged**
